wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
arch:
  desc: null
  value: BNInception
batch_size:
  desc: null
  value: 64
clip_gradient:
  desc: null
  value: 20
consensus_type:
  desc: null
  value: TRN
data_length:
  desc: null
  value: 3
dataset:
  desc: null
  value: dai
dropout:
  desc: null
  value: 0.8
epochs:
  desc: null
  value: 120
eval_freq:
  desc: null
  value: 5
evaluate:
  desc: null
  value: false
flow_prefix:
  desc: null
  value: ''
gamma:
  desc: null
  value: 1.0
gpus:
  desc: null
  value: null
hand:
  desc: null
  value: false
img_feature_dim:
  desc: null
  value: 256
k:
  desc: null
  value: 3
lamdb_hand:
  desc: null
  value: 1.0
loss_subtype:
  desc: null
  value: focal
loss_type:
  desc: null
  value: nll
lr:
  desc: null
  value: 0.001
lr_steps:
  desc: null
  value:
  - 50
  - 100
margin:
  desc: null
  value: 1.5
modality:
  desc: null
  value: RGB
momentum:
  desc: null
  value: 0.9
no_partialbn:
  desc: null
  value: false
num_segments:
  desc: null
  value: 3
print_freq:
  desc: null
  value: 20
resume:
  desc: null
  value: ''
resume_of:
  desc: null
  value: ''
root_log:
  desc: null
  value: /dresden/gpu2/tl6012/TRN-test/log
root_model:
  desc: null
  value: /dresden/gpu2/tl6012/TRN-test/model
root_output:
  desc: null
  value: /dresden/gpu2/tl6012/TRN-test/output
root_path:
  desc: null
  value: /dresden/gpu2/tl6012/data/ASL/isolated_signs
siamese:
  desc: null
  value: false
snapshot_pref:
  desc: null
  value: ''
start_epoch:
  desc: null
  value: 0
store_name:
  desc: null
  value: TRN_dai_RGB_BNInception_TRN_segment3_newL3_lossnll_bs64
train_list:
  desc: null
  value: ./dai/train_videofolder_20_hand.txt
val_list:
  desc: null
  value: ./dai/val_videofolder_20_hand.txt
weight_decay:
  desc: null
  value: 0.0005
workers:
  desc: null
  value: 8
